" Use syntax
syntax on
" turn on line numbers; may need to toggle off for pasting
set number
" turn on indentation
filetype plugin indent on
" set filename autocompletion to be bash-like
set wildmode=longest:full
set wildmenu
" Colors
colorscheme desert
" Incrementral (smart) search
set incsearch
set ignorecase
set smartcase
" Make sure I have at least a few lines of context when editing
set scrolloff=2
" Show line number and column in status bar
set ruler
" Experimental python code additions from
" http://dancingpenguinsoflight.com/2009/02/python-and-vim-make-your-own-ide/
let python_highlight_all = 1
