#!/bin/bash
# This hook is run after every virtualenv is activated.

export VE_OLD_PYTHONPATH=$PYTHONPATH
export PYTHONPATH=
# Clear user Python binary path
export PATH=$(echo $PATH | sed "s|${PY_USER_BIN}:\{0,1\}||")
